version: "3"

services:
  trezor-user-env-unix:
    container_name: trezor-user-env.unix
    image: ghcr.io/trezor/trezor-user-env
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      # NOTE: it is possible to combine docker container and hardware device,
      # but only for Linux, and only if the Trezor bridge is running locally.
      # Second option of running with HW device is running the whole `tenv` locally.
      - PHYSICAL_TREZOR=1
    volumes:
      - ./../logs/screens:/trezor-user-env/logs/screens
      - ./../src/binaries/firmware/bin/user_downloaded:/trezor-user-env/src/binaries/firmware/bin/user_downloaded
  trezor-user-env-regtest:
    container_name: trezor-user-env-regtest
    image: ghcr.io/trezor/trezor-user-env-regtest
    ports:
      - "19021:19021" # internal blockbook port
      - "19121:19121" # public blockbook port for website dashboard
      - "18021:18021" # bitcoin-d rpc port