export const ETHEREUM_CHAIN_ID = 1
export const BASE_CHAIN_ID = 8453
export const OPTIMISM_CHAIN_ID = 10
export const ARBITRUM_CHAIN_ID = 42161
export const SCROLL_CHAIN_ID = 534352

export const LEGENDS_SUPPORTED_NETWORKS_BY_CHAIN_ID = [
  ETHEREUM_CHAIN_ID,
  BASE_CHAIN_ID,
  OPTIMISM_CHAIN_ID,
  ARBITRUM_CHAIN_ID,
  SCROLL_CHAIN_ID
]
