require_relative '../node_modules/expo/scripts/autolinking'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}
inhibit_all_warnings!


target 'ambire' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #
  # Using `"Flipper-DoubleConversion" => "1.1.7"` resolves the following warns:
  #  ⚠️  ld: duplicate symbol 'folly::detail::str_to_bool(folly::Range<char const*>*)' in
  #   ┌─ libFlipper-Folly.a(Conv.o)
  #   └─ libRCT-Folly.a(Conv.o)
  #
  #  ⚠️  ld: duplicate symbol 'folly::makeConversionError(folly::ConversionCode, folly::Range<char const*>)' in
  #   ┌─ libFlipper-Folly.a(Conv.o)
  #   └─ libRCT-Folly.a(Conv.o)
  # {@link https://github.com/facebook/react-native/issues/32016#issuecomment-979897732}
  use_flipper!("Flipper" => "0.159.0", "Flipper-DoubleConversion" => "1.1.7")

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by
    # default when building for devices.
    # {@link https://expo.fyi/r/disable-bundle-resource-signing}
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

end
