const COMMON_ROUTES = {
  keyStoreUnlock: 'keystore-unlock',
  resetVault: 'reset-vault',
  getStarted: 'get-started',
  createVault: 'create-vault',
  auth: 'auth',
  ambireAccountLogin: 'ambire-account-email-login',
  externalSigner: 'external-signer',
  accountAdder: 'account-adder',
  dashboard: 'dashboard',
  collectible: 'collectible',
  earn: 'earn',
  transfer: 'transfer',
  topUpGasTank: 'top-up-gas-tank',
  signAccountOp: 'sign-account-op',
  transactions: 'transactions',
  signedMessages: 'signed-messages',
  gasTank: 'gas-tank',
  pendingTransactions: 'pending-transactions',
  receive: 'receive',
  provider: 'provider',
  signMessage: 'sign-message',
  gasInformation: 'gas-information',
  signers: 'signers',
  menu: 'menu',
  swap: 'swap',
  noConnection: 'no-connection',
  backup: 'backup',
  accounts: 'accounts',
  appCatalog: 'app-catalog'
}

const MOBILE_ROUTES = {
  ...COMMON_ROUTES,
  addReferral: 'add-referral',
  connect: 'connect',
  dataDeletionPolicy: 'data-deletion-policy',
  manageVaultLock: 'manage-vault-lock',
  onboardingOnFirstLogin: 'onboarding-on-first-login',
  noConnection: 'no-connection',
  hardwareWallet: 'hardware-wallet',
  web3Browser: 'web3-browser',
  enableOtp2FA: 'enable-otp-2fa',
  disableOtp2FA: 'disable-otp-2fa'
}

const WEB_ROUTES = {
  ...COMMON_ROUTES,
  inviteVerify: 'invite-verify',
  terms: 'terms',
  keyStoreSetup: 'keystore-setup',
  keyStoreReset: 'keystore-reset',
  getEncryptionPublicKeyRequest: 'get-encryption-public-key-request',
  dappConnectRequest: 'dapp-connect-request',
  watchAsset: 'watch-asset',
  addChain: 'add-chain',
  switchAccount: 'switch-account',
  hardwareWalletSelect: 'hardware-wallet/select',
  hardwareWalletReconnect: 'hardware-wallet/reconnect',
  hardwareWalletLedger: 'hardware-wallet/ledger',
  authEmailAccount: 'auth-email-account',
  authEmailLogin: 'auth-email-login',
  authEmailRegister: 'auth-email-register',
  accountPersonalize: 'account-personalize',
  accountSelect: 'account-select',
  viewOnlyAccountAdder: 'view-only-account-adder',
  networks: 'networks',
  generalSettings: 'settings/general',
  settingsTerms: 'settings/terms',
  settingsAbout: 'settings/about',
  networksSettings: 'settings/networks',
  accountsSettings: 'settings/accounts',
  basicToSmartSettingsScreen: 'settings/accounts/basic-to-smart',
  exportKey: 'settings/accounts/exportKey',
  devicePasswordSet: 'settings/device-password-set',
  devicePasswordChange: 'settings/device-password-change',
  devicePasswordRecovery: 'settings/device-password-recovery',
  addressBook: 'settings/address-book',
  manageTokens: 'settings/manage-tokens',
  importHotWallet: 'import-hot-wallet',
  importPrivateKey: 'import-private-key',
  importSmartAccountJson: 'import-smart-account-json',
  importSeedPhrase: 'import-seed-phrase',
  createHotWallet: 'create-hot-wallet',
  createSeedPhrasePrepare: 'create-seed-phrase/prepare',
  createSeedPhraseWrite: 'create-seed-phrase/write',
  createSeedPhraseConfirm: 'create-seed-phrase/confirm',
  benzin: 'benzin',
  swapAndBridge: 'swap-and-bridge',
  savedSeed: 'saved-seed',
  securityAndPrivacy: 'settings/security-and-privacy',
  saveImportedSeed: 'save-imported-seed'
}

const WEB_ROUTES_TITLES = {
  [WEB_ROUTES.noConnection]: 'No Connection',
  [WEB_ROUTES.keyStoreSetup]: 'Key Store Setup',
  [WEB_ROUTES.keyStoreReset]: 'Key Store Reset',
  [WEB_ROUTES.getStarted]: 'Get Started',
  [WEB_ROUTES.terms]: 'Terms',
  [WEB_ROUTES.authEmailAccount]: 'Email Account',
  [WEB_ROUTES.authEmailLogin]: 'Email Login',
  [WEB_ROUTES.authEmailRegister]: 'Email Register',
  [WEB_ROUTES.importHotWallet]: 'Import Hot Wallet',
  [WEB_ROUTES.hardwareWalletSelect]: 'Select Hardware Wallet',
  [WEB_ROUTES.hardwareWalletReconnect]: 'Reconnect Hardware Wallet',
  [WEB_ROUTES.viewOnlyAccountAdder]: 'Add View Only Account',
  [WEB_ROUTES.importPrivateKey]: 'Import Private Key',
  [WEB_ROUTES.importSeedPhrase]: 'Import Seed Phrase',
  [WEB_ROUTES.importSmartAccountJson]: 'Import Smart Account JSON',
  [WEB_ROUTES.createHotWallet]: 'Create Hot Wallet',
  [WEB_ROUTES.createSeedPhrasePrepare]: 'Prepare Seed Phrase',
  [WEB_ROUTES.createSeedPhraseWrite]: 'Write Seed Phrase',
  [WEB_ROUTES.createSeedPhraseConfirm]: 'Confirm Seed Phrase',
  [WEB_ROUTES.accountAdder]: 'Add Account',
  [WEB_ROUTES.accountPersonalize]: 'Personalize Account',
  [WEB_ROUTES.saveImportedSeed]: 'Save Imported Seed',
  [WEB_ROUTES.transfer]: 'Transfer',
  [WEB_ROUTES.topUpGasTank]: 'Top Up Gas Tank',
  [WEB_ROUTES.swapAndBridge]: 'Swap and Bridge',
  [WEB_ROUTES.generalSettings]: 'General Settings',
  [WEB_ROUTES.securityAndPrivacy]: 'Security and Privacy',
  [WEB_ROUTES.accountsSettings]: 'Accounts Settings',
  [WEB_ROUTES.basicToSmartSettingsScreen]: 'Basic to Smart Settings',
  [WEB_ROUTES.exportKey]: 'Export Key',
  [WEB_ROUTES.savedSeed]: 'Saved Seed',
  [WEB_ROUTES.networksSettings]: 'Networks',
  [WEB_ROUTES.transactions]: 'Transaction History',
  [WEB_ROUTES.signedMessages]: 'Signed Messages History',
  [WEB_ROUTES.devicePasswordSet]: 'Set Device Password',
  [WEB_ROUTES.devicePasswordChange]: 'Change Device Password',
  [WEB_ROUTES.devicePasswordRecovery]: 'Recover Device Password',
  [WEB_ROUTES.manageTokens]: 'Manage Tokens',
  [WEB_ROUTES.addressBook]: 'Address Book',
  [WEB_ROUTES.settingsTerms]: 'Terms of Service',
  [WEB_ROUTES.settingsAbout]: 'About',
  [WEB_ROUTES.signAccountOp]: 'Sign Account Operation',
  [WEB_ROUTES.signMessage]: 'Sign Message',
  [WEB_ROUTES.benzin]: 'Benzin',
  [WEB_ROUTES.switchAccount]: 'Switch Account',
  [WEB_ROUTES.dappConnectRequest]: 'Dapp Connect Request',
  [WEB_ROUTES.addChain]: 'Add Chain',
  [WEB_ROUTES.watchAsset]: 'Watch Asset',
  [WEB_ROUTES.getEncryptionPublicKeyRequest]: 'Get Encryption Public Key Request',
  [WEB_ROUTES.menu]: 'Menu',
  [WEB_ROUTES.accountSelect]: 'Select Account',
  [WEB_ROUTES.appCatalog]: 'Dapp Catalog',
  [WEB_ROUTES.networks]: 'Networks',
  [WEB_ROUTES.keyStoreUnlock]: 'Key Store Unlock',
  [WEB_ROUTES.resetVault]: 'Reset Vault',
  [WEB_ROUTES.createVault]: 'Create Vault',
  [WEB_ROUTES.auth]: 'Auth',
  [WEB_ROUTES.ambireAccountLogin]: 'Account Login',
  [WEB_ROUTES.externalSigner]: 'External Signer',
  [WEB_ROUTES.dashboard]: 'Dashboard',
  [WEB_ROUTES.collectible]: 'Collectible',
  [WEB_ROUTES.earn]: 'Earn',
  [WEB_ROUTES.gasTank]: 'Gas Tank',
  [WEB_ROUTES.pendingTransactions]: 'Pending Transactions',
  [WEB_ROUTES.receive]: 'Receive',
  [WEB_ROUTES.provider]: 'Provider',
  [WEB_ROUTES.gasInformation]: 'Gas Information',
  [WEB_ROUTES.signers]: 'Signers',
  [WEB_ROUTES.backup]: 'Backup',
  [WEB_ROUTES.accounts]: 'Accounts'
}

const ROUTES = {
  ...COMMON_ROUTES,
  ...MOBILE_ROUTES,
  ...WEB_ROUTES
}

export { ROUTES, MOBILE_ROUTES, WEB_ROUTES, WEB_ROUTES_TITLES }
