export const locators = {
  watchAnAddress: 'div[data-testid="view-only-address-btn"]',
  viewOnlyInputAddressField: 'input[data-testid="view-only-address-field-0"]',
  importViewOnlyButton: 'div[data-testid="view-only-button-import"]',
  enterPasswordField: 'input[data-testid="enter-pass-field"]',
  repeatPasswordField: 'input[data-testid="repeat-pass-field"]',
  confirmButton: 'div[data-testid="create-keystore-pass-btn"]',
  confirmationMessageForViewOnly: 'div:has-text("Added successfully")',
  completeButton: 'div[data-testid="button-save-and-continue"]',
  confirmationMessageAmbireWallet: 'div:has-text("Ambire Wallet is ready to use") >> nth=0',
  openDashboardButton: 'div[data-testid="onboarding-completed-open-dashboard-btn"]',
  dashboadHabmurgerButton: 'div[data-testid="dashboard-hamburger-btn"]',
  createNewAccountButton: 'div[data-testid="create-new-account-btn"]',
  createRecoveryPhraseButton: 'div[data-testid="review-seed-phrase-btn"]',
  copyRecoveryPhraseButton: 'div[data-testid="copy-recovery-phrase"]',
  recoveryPhraseHeader: 'div:has-text("Back up recovery phrase") >> nth=0',
  savedPhraseButton: 'div[data-testid="create-seed-phrase-write-continue-btn"]',
  addMoreAccountsButton: 'div[data-testid="add-more-accounts-btn"]',
  importExistingAccountButton: 'div[data-testid="create-existing-account-btn"]',
  importFromPrivateKeyButton: 'div[data-testid="import-method-private-key"]',
  inputPrivateKey: 'input[data-testid="enter-seed-phrase-field"]',
  warningCheckbox: 'div[data-testid="backup-warning-checkbox"]',
  importConfirmButton: 'div[data-testid="import-button"]',
  importFromRecoveryPhraseButton: 'div[data-testid="import-method-recovery-phrase"]',
  inputSeetField: 'textarea[data-testid="enter-seed-phrase-field"]',
  recoveryPhraseAdvancedModeToggle: 'label[testid="enable-passphrase-toggle"]',
  inputPassphrase: 'input[data-testid="input-passphrase"]',
  editAccountButton: 'div[data-testid="edit-btn-for-edit-name-field-0"]',
  editAccountNameField: 'input[data-testid="edit-name-field-0"]',
  saveMessageText: 'div[data-testid="text-save"]',
  addMoreAdressesButton: 'div[data-testid="add-one-more-address"]',
  viewOnlySecondInputAddressField: 'input[data-testid="view-only-address-field-1"]',
  addAccount: 'div[data-testid="button-add-account"]',
  smartAccountPicker: 'div[data-testid^="add-account-"] >> nth=5',
  smartAccountPickerForHDPath: 'div[data-testid^="add-account-"] >> nth=5',
  importAccountButton: 'div[data-testid="button-import-account"]',
  changeHDPathButton: 'div[data-testid="change-hd-path-btn"]',
  hdPathLegerLive: 'div[data-testid="hd-path-option-ledger-live"]',
  hdPathLegerLegacy: 'div[data-testid="hd-path-option-ledger-legacy"]',
  hdPathConfirmButton: 'div[data-testid="hd-path-confirm-btn"]'
}
